sudo: required

dist: trusty

language: node_js

node_js: stable

cache:
  directories:
    - node_modules

script:
  - "npm run lint"
  - "npm run unit -- --coverage"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: tests/unit/coverage/lcov-report
  on:
    branch: master
