export const ADD_TO_SELECTION = 'ADD_TO_SELECTION'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const RECEIVE_STARSHIPS = 'RECEIVE_STARSHIPS'
export const REMOVE_FROM_SELECTION = 'REMOVE_FROM_SELECTION'
