export const RECEIVE_STARSHIPS = 'RECEIVE_STARSHIPS'
export const INCREMENT_PAGE = 'INCREMENT_PAGE'

export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
export const INCREMENT_BASKET_ITEM = 'INCREMENT_BASKET_ITEM'
